# Array Manipulation

# Array Manipulation - Changing Shape

In [1]:
import numpy as np
a = np.arange(9)
print("The original array: ")
print(a)

b=a.reshape(3,3)
print("The modified array: ")
print(b)

The original array: 
[0 1 2 3 4 5 6 7 8]
The modified array: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [6]:
a = np.arange(1,13,1).reshape(4,3)

In [7]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
b = np.transpose(a)
b

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [10]:
b.shape

(3, 4)

In [18]:
b=np.arange(8).reshape(2,2,2)

In [19]:
b

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
np.rollaxis(b,2,0)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

# Numpy Arithmetic Operations

In [24]:
a = np.arange(9).reshape(3,3)

In [25]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [27]:
np.add(a,b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [28]:
np.subtract(a,b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [29]:
np.multiply(a,b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

# Slicing

In [30]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
a[:4]

array([0, 1, 2, 3])

In [32]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
a[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [34]:
a[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [35]:
s = slice(2,12,3)
a[s]

array([ 2,  5,  8, 11])

# Iterating Over Array

In [37]:
a = np.arange(0,45,5)
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [38]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


# Iteration over (C style and F style)

In [39]:
print(a)
for x in np.nditer(a, order = 'C'):
    print(x)


[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40


In [40]:
for x in np.nditer(a,order='F'):
    print(x)

0
15
30
5
20
35
10
25
40


# Adding two arrays

In [43]:
a = np.array([[1,2,],[4,5]])
print('first array')
print(a)
b = np.array([[5,6],[7,8]])
print('Second Array')
print(b)
print('\n')
print('Joining the two arrays along axis o: ')
print(np.concatenate((a,b)))
print('\n')
print('Joining the two arrays along axis 1: ')
print(np.concatenate((a,b),axis =1))
print('\n')


first array
[[1 2]
 [4 5]]
Second Array
[[5 6]
 [7 8]]


Joining the two arrays along axis o: 
[[1 2]
 [4 5]
 [5 6]
 [7 8]]


Joining the two arrays along axis 1: 
[[1 2 5 6]
 [4 5 7 8]]




# Splitting Array

In [45]:
a = np.arange(9)
print(a)
np.split(a,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [46]:
np.split(a,[4,5,6])

[array([0, 1, 2, 3]), array([4]), array([5]), array([6, 7, 8])]

In [47]:
np.split(a,[4,7])

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]